### ISSUE TITLE
Custom Query Parameters not Supported

### ISSUE THREAD

**Issue by morgansierrasnyder** [classy-org/classy-pay-client#9]
Currently, `classy-pay-client` only supports the the following parameters in the query string of a request: `appId`, `limit`, `offset`, and `meta` (which is defaulted to true)

This limitation is an issue when hitting the token endpoints. For example, the tokenex fetch endpoint `GET` `{host}/token/tokenex` requires both `appId` and `origin` to be specified in the request's query string. The bitpay endpoint `GET` `{host}/token/bitpay` also requires custom query parameters, `amount` and `email`.

Could you guys consider adding an optional object argument (either identical to `pagination`, or you can combine the two) that could be used to specify additional query params?

Implementation example:
```
function getOptions(appId, method, resource, payload, queryParams) {
  return {
    method,
    url: `${config.apiUrl}${resource}`,
    qs: getQs(appId, query),
    body: payload ? JSON.stringify(payload) : null,
    timeout: config.timeout,
    headers: getHeaders(method, resource, payload)
  };
}

function getQs(appId, queryParams) {
  return {
    appId,
    meta: true,
    ...queryParams
  };
}
```

**Comment by jnngrm** [comment]
Quite reasonable ... i'm not sure the node version in lambda support the spread operator ... but hopefully it does :-).

**Comment by jnngrm** [comment]
Just checked, spread operator is supported
